### PR TITLE
Hardware loop of keysight pxi systems. Also backplane triggering.

### PR DESCRIPTION
**Pull request by andbe91**

### CODE REVIEW

**Comment by andbe91** [comment]
Hi @simongus, I'm working on some bug fixes and new features for this. So please hold off with the merging of this PR.

**Comment by simongus** [comment]
sounds good - let's make a test run on a real qubit before merging into master

**Comment by andbe91** [comment]
Hi @simongus, this should now be ready to merge.
Due to the re-structuring of the ini-file, I'm guessing that this will most likely break already created measurement configs? Is there a good way to handle this?

**Comment by simongus** [comment]
You can make them compatible by implementing a "-UpgradeCfg.py" function.  This allows you to define what should happen when renaming/type converting quantities. It's poorly documented, but see the Yoko 7651 driver for an example:
https://github.com/Labber-software/Drivers/blob/master/Yokogawa_7651/Yokogawa_7651-UpgradeCfg.py

I'm not sure it's worth doing in this case, given that there are a large number of changes (?)

**Pull request merged**
