### PR TITLE
multi-qubit rb

### PR DESCRIPTION
**Pull request by Youngkyu-Sung**
- Keep the format of psi and unitary gates consistent with other drivers.
ground state = [0, 1]
excited state = [1, 0]

- See http://www.vcpc.univie.ac.at/~ian/hotlist/qc/talks/bloch-sphere-rotations.pdf  for details.

### CODE REVIEW

**Comment by mollieks** [comment]
Hi Jack,

I'm not sure how the drivers handle this, but within the QC community it's almost universally the convention that |0> = [1, 0] and |1> = [0, 1]. I would recommend using that convention to avoid mistakes from future developers who make that assumption.

Mollie

**Comment by Youngkyu-Sung** [comment]
Hi Mollie,

Thank you for your comment. I just checked M. Nielsen, I. Chuang's textbook(http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf) and J. Preskills' lecture notes(http://www.theory.caltech.edu/~preskill/ph219/ph219_2013-14) and found out that you are right! I will correct the format.

Thank you!
Youngkyu

**Comment by simongus** [comment]
sounds good!  It doesn't matter from a mathematical point of view, but I agree that it's much better to use conventions when they exist.
@Youngkyu-Sung what other drivers are using the other format?  Single-qubit pulse generator and simulator?

**Comment by Youngkyu-Sung** [comment]
Hi @simongus ,
Single-qubit simulator uses the same format which Mollie says(|0> = [1, 0] and |1> = [0, 1]). Only the new three-level qubit simulator which is not published yet uses the different format. I will correct this one.

**Pull request merged**
